# Site settings
title: The Newsprint
email: josh@thenewsprint.co
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beta.thenewsprint.co" # the base hostname & protocol for your site
twitter_username: thenewsprint

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude: ['/node_modules/','**.sublime-project','**.sublime-workspace','gruntfile.js','package.json','.git']
paginate: 20